apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api
spec:
  selector:
    matchLabels:
      app: pokemon-api
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
      - name: pokemon-api
        image: pokemon-api
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-api
spec:
  selector:
    app: pokemon-api
  ports:
  - port: 80
    targetPort: http


